version: '3'

services:
  app:
    image: cyrilschreiber/better-uptime-bot:latest
    # build: . # use this line to build the image locally
    container_name: betteruptimebot_app
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - internal
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: betteruptimebot_db
    restart: unless-stopped
    networks:
      - internal
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - ./db_data:/var/lib/mysql

networks:
  internal:
    driver: bridge
